ALTER TABLE todos ADD COLUMN subtasks TEXT;
ALTER TABLE todos ADD COLUMN image_url TEXT;

CREATE TABLE IF NOT EXISTS birthdays (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  date TEXT NOT NULL
);

